name: CD

on:
  push:
    branches:
      - maineeeeeee

jobs:
  deployed:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload app via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          source: "front/out"
          target: "/var/www/httpdocs/"
