name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - prod
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: install checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: maven
          cache-dependency-path: back/pom.xml

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build jar
        run: ./mvnw clean package -DskipTests

  renovate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.17
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
